name: Feature Request | 功能请求
description: General Feature request
title: "[Feature]: "
labels: []
assignees: []
body:
- type: markdown
  attributes:
    value: |
      **Thanks for taking a minute to file a feature request!**
      **感谢抽出时间提出新功能！**

      ⚠ Read before creating issue 反馈之前请注意:
      Only request feature here, please use the [Discussion board][discussion-board] for non-bug, troubleshooting or general discusion.
      非新功能的反馈（疑难解答，行为建议，常规讨论）请转到 [Discussion 面板][discussion-board]

      [discussion-board]: https://github.com/linuxdeepin/treeland/discussions

- type: textarea
  attributes:
    label: SUMMARY | 功能概要
    description: |
      describe the feature you want to request
      在这里描述你想提出的新功能

